name: "JavaScript Test Action"
description: "JavaScript Test Action"
author: "Shane"
branding:
  icon: "type"
  color: "green"

inputs:
  body:
    description: "Test Body"
    required: false

outputs:
  result:
    description: "Result Output"

runs:
  using: "node20"
  main: "dist/index.js"
