name: 'Docker Tags Test Action'
description: 'Parse Docker Tags'
author: 'Shane'
branding:
    icon: 'tag'
    color: 'blue'

inputs:
    images:
        description: 'Image Names to Tag'
        required: true
    extra:
        description: 'Extra Tags to Add'
        required: false
        default: ''
    seperator:
        description: 'Tags Output Seperator'
        required: false
        default: '\n'
    latest:
        description: 'Add latest Tag'
        required: false
        default: 'default'
    prefix:
        description: 'Semantic Tag Prefix'
        required: false
        default: ''

outputs:
    tags:
        description: 'Generated Docker tags'

runs:
    using: 'node20'
    main: 'dist/index.js'
