name: 'Hello World'
description: 'Greet someone and record the time'
author: 'Shane'

inputs:
  chrome:
    description: 'Chrome Archive Location'
    required: false
    default: ''
  firefox:
    description: 'Firefox Archive Location'
    required: false
#    default:

#outputs:
#  time:
#    description: 'The time we greeted you'

runs:
  using: 'node20'
  main: 'dist/index.js'
