name: "Test"

on:
  workflow_dispatch:
  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          body: "Test Body"

      - name: "Echo Outputs"
        run: |
          echo '${{ steps.test.outputs.result }}'
