name: "Test"

on:
  workflow_dispatch:
  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "JS Test Action"
        id: update
        uses: smashedr/js-test-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "Test Body"

      - name: "Echo Output"
        run: |
          echo '${{ steps.update.outputs.result }}'
